### ISSUE TITLE
New projects broken: require statement not part of import statement

### ISSUE THREAD

**Issue by sburris0** [vuejs/vue-apollo#1106]
**Describe the bug**
```
Done in 7.27s.
Successfully installed plugin: vue-cli-plugin-apollo

? Add example code No
? Add a GraphQL API Server? No
? Configure Apollo Engine? No

Invoking generator for vue-cli-plugin-apollo...
 Running completion hooks...error: Require statement not part of import statement (@typescript-eslint/no-var-requires) at apollo.config.js:1:14:
> 1 | const path = require('path')
    |              ^
  2 | 
  3 | // Load .env files
  4 | const { loadEnv } = require('vue-cli-plugin-apollo/utils/load-env')


error: Require statement not part of import statement (@typescript-eslint/no-var-requires) at apollo.config.js:4:21:
  2 | 
  3 | // Load .env files
> 4 | const { loadEnv } = require('vue-cli-plugin-apollo/utils/load-env')
    |                     ^
  5 | const env = loadEnv([
  6 |   path.resolve(__dirname, '.env'),
  7 |   path.resolve(__dirname, '.env.local')


2 errors found.
```

**To Reproduce**
1. `vue create someapp`
2. Select vue 2, typescript support, CSS preprocessor, everything else is default
3. `vue add apollo`
4. Observe error messages shown above

**Expected behavior**
I expect new projects to not have errors before I edit anything myself.

**Versions**
vue: 2.6.11
vue-apollo: 3.0.0-beta.11
apollo-client: n/a

**Comment by c0bra** [comment]
Same issue here.

**Comment by Jason0715** [comment]
The reason for this problem may be that you use eslint .
You can try to add rules in the .eslintrc.js file.
rules: {
    '@typescript-eslint/no-var-requires': 0,
}

**Comment by Jason0715** [comment]
The reason for this problem may be that you use eslint .
You can try to add rules in the .eslintrc.js file.

rules: {
    '@typescript-eslint/no-var-requires': 0,
}

**Comment by kimbaudi** [comment]
> You can try to add rules in the .eslintrc.js file.
rules: {
'@typescript-eslint/no-var-requires': 0,
}

although this works, you are essentially disabling this eslint rule throughout your application just so you don't see this error in your `apollo.config.js` file (which btw isn't even a .ts file). 

A better approach would be to simply disable this eslint rule just for the `apollo.config.js` file.

An even better approach would be to configure eslint so it only applies this rules to .`ts/.tsx` files where it applies.
