### ISSUE TITLE
clean installation `$ vue create` with typescript + `$ vue add apollo` error

### ISSUE THREAD

**Issue by kidfrom** [vuejs/vue-apollo#995]
**Describe the bug**

Clean installation `$ vue create` with TypeScript + `$ vue add apollo` results in ESLint error.

**To Reproduce**

1. Create vue project

    ```
    $ vue create name
    Vue CLI v4.4.1
    ? Please pick a preset: Manually select features
    ? Check the features needed for your project: Babel, TS, PWA, Router, Vuex, Linter
    ? Use class-style component syntax? Yes
    ? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
    ? Use history mode for router? (Requires proper server setup for index fallback in production) No
    ? Pick a linter / formatter config: Basic
    ? Pick additional lint features: Lint on save
    ? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
    ? Save this as a preset for future projects? No
    ```

2. Add Apollo Boost

    ```
    $ vue add apollo
    ? Add example code Yes
    ? Add a GraphQL API Server? No
    ? Configure Apollo Engine? No
    ```

3. TypeScript ESLint report `error: Require statement not part of import statement (@typescript-eslint/no-var-requires) at apollo.config.js` on line 14 and 21.

    ```
    Running completion hooks...error: Require statement not part of import statement (@typescript-eslint/no-var-requires) at apollo.config.js:1:14:
    > 1 | const path = require('path')
        |              ^
    2 |
    3 | // Load .env files
    4 | const { loadEnv } = require('vue-cli-plugin-apollo/utils/load-env')


    error: Require statement not part of import statement (@typescript-eslint/no-var-requires) at apollo.config.js:4:21:
    2 |
    3 | // Load .env files
    > 4 | const { loadEnv } = require('vue-cli-plugin-apollo/utils/load-env')
        |                     ^
    5 | const env = loadEnv([
    6 |   path.resolve(__dirname, '.env'),
    7 |   path.resolve(__dirname, '.env.local')


    2 errors found.
    ```

**Expected behavior**

No errors found.

**Versions**
vue: ^2.6.11
vue-apollo: ^3.0.0-beta.11

**Comment by kidfrom** [comment]
I will close this issue as I am no longer using apollo boost.
